steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/the-biblical-man/app:$COMMIT_SHA'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=$_GEMINI_API_KEY'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/the-biblical-man/app:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'the-biblical-man'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/the-biblical-man/app:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/the-biblical-man/app:$COMMIT_SHA'

# Default substitution variables (can be overridden in trigger settings)
substitutions:
  _GEMINI_API_KEY: 'AIzaSyCmb1G6GXtiA5dRE6Szfez5DUUmaiejchw'

options:
  logging: CLOUD_LOGGING_ONLY
